version: "3.8"

services:
  opa:
    image: openpolicyagent/opa:latest
    environment:
      - NODE_ENV=dev
    ports:
      - 8181:8181
    volumes:
      - ./src:/src
    command:
      - run
      - --server
      - -w
      - /src